# Generated by Django 4.0.1 on 2022-04-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operation', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
