# Generated by Django 4.0.1 on 2022-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operation', '0004_alter_book_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
